services:


  signal-api:
    image: bbernhard/signal-cli-rest-api:latest
    environment:
      - MODE=native
    ports:
      - "8756:8080"
    volumes:
      - ./signal-cli-data:/home/.local/share/signal-cli
    restart: always
  signal-watcher:
    build: ./signal-watcher
    volumes:
      - ./signal-watcher:/app
      - signal-watcher-node-modules:/app/node_modules
    environment:
      SIGNAL_NUMBER: "+15107302276"
      SIGNAL_API: "http://signal-api:8080"
      MU_API_URL: "http://mu-app:5176/api/v1/webhooks/signal"
      DELAY_RANGE: "3,12"
    depends_on:
      - signal-api
    restart: always

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate --url http://mu-app:5173 run --token ${CF_TOKEN}
    restart: always
    environment:
      - CF_TOKEN

  # mu-app:
  #   build:
  #     context: ./mu-app
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5176:5176"  # backend API (adjust if different)
  #     - "5173:5173"  # frontend dev (adjust if different)
  #   volumes:
  #     - ./mu-app:/app  # enables live editing
  #   command: >
  #     sh -c "concurrently \
  #       \"nodemon --watch mu-api --ext js,ts --exec \\\"npm --prefix mu-api run dev\\\"\" \
  #       \"nodemon --watch mu-admin --ext js,ts,jsx,tsx --exec \\\"npm --prefix mu-admin run dev\\\"\" \
  #       \"nodemon --watch mu-hex-api --ext js,ts --exec \\\"npm --prefix mu-hex-api run dev\\\"\""
  #   environment:
  #     - NODE_ENV=development
  #     - CHOKIDAR_USEPOLLING=true  # needed for Vite polling in Docker
  #     - SIGNAL_NUMBER=+15107302276
  #   depends_on:
  #     - signal-api
  #   restart: always

  # nginx:
  #   build: 
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8755:8755"
  #   depends_on:
  #     - flask
  #   # volumes:
  #   #   - /home/austin/log/nginx:/var/log/nginx
  #   restart: always
  # mu-app:
  #   build:
  #     context: ./mu-app
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5176:5176"  # backend API (adjust if different)
  #     - "5173:5173"  # frontend dev (adjust if different)
  #   volumes:
  #     - ./mu-app:/app  # enables live editing
  #   command: >
  #     sh -c "concurrently \
  #       \"nodemon --watch mu-api --ext js,ts --exec \\\"npm --prefix mu-api run dev\\\"\" \
  #       \"nodemon --watch mu-admin --ext js,ts,jsx,tsx --exec \\\"npm --prefix mu-admin run dev\\\"\" \
  #       \"nodemon --watch mu-hex-api --ext js,ts --exec \\\"npm --prefix mu-hex-api run dev\\\"\""
  #   environment:
  #     - NODE_ENV=development
  #     - CHOKIDAR_USEPOLLING=true  # needed for Vite polling in Docker
  #     - SIGNAL_NUMBER=+15107302276
  #   depends_on:
  #     - signal-api
  #   restart: always

  # flask:
  #   build: 
  #     context: ./flask_app
  #     dockerfile: Dockerfile
  #   environment:
  #     - FLASK_RUN_HOST=0.0.0.0
  #   restart: always
  #   stop_signal: SIGINT

  # mu-hex-admin:
  mu-hex-admin-old:
    build:
      context: ./mu-hex-admin-old
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./mu-hex-admin-old:/app
      - mu-hex-admin-node-modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
    restart: always

volumes:
  signal-watcher-node-modules:
  mu-hex-admin-node-modules: