version: '3.8'

services:
  flask:
    build: 
      context: ./flask_app
      dockerfile: Dockerfile
    environment:
      - FLASK_RUN_HOST=0.0.0.0
    restart: always

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8755:8755"
    depends_on:
      - flask
    # volumes:
    #   - /home/austin/log/nginx:/var/log/nginx
    restart: always

  signal-api:
    image: bbernhard/signal-cli-rest-api:latest
    environment:
      - MODE=native
    ports:
      - "8756:8080"
    volumes:
      - ./signal-cli-data:/home/.local/share/signal-cli
    restart: always

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CF_TOKEN}
    restart: always
    environment:
      - CF_TOKEN

  test-runner:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - .:/app
    command: >
      sh -c "pip install --no-cache-dir -r requirements-dev.txt && pytest --tb=short -q tests"
    depends_on:
      - flask
      - signal-api

networks:
  default:
    ipam:
      config:
        - subnet: 172.29.0.0/16