version: '3.8'

services:
  flask:
    build: 
      context: ./flask_app
      dockerfile: Dockerfile
    environment:
      - FLASK_RUN_HOST=0.0.0.0
    restart: always
    stop_signal: SIGINT

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8755:8755"
    depends_on:
      - flask
    # volumes:
    #   - /home/austin/log/nginx:/var/log/nginx
    restart: always

  signal-api:
    image: bbernhard/signal-cli-rest-api:latest
    environment:
      - MODE=native
    ports:
      - "8756:8080"
    volumes:
      - ./signal-cli-data:/home/.local/share/signal-cli
    restart: always
  signal-watcher:
    build:
      context: ./signal-watcher
    environment:
      - SIGNAL_NUMBER=+15107302276
      - SIGNAL_API=http://signal-api:8080
      - WEBHOOK_URL=https://uopvhhbushcwwqpbswpm.supabase.co/functions/v1/receive-from-signal
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - DELAY_RANGE=3,12
    depends_on:
      - signal-api
    restart: always

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CF_TOKEN}
    restart: always
    environment:
      - CF_TOKEN

  # mu-dash: React Admin Dashboard
  mu-dash:
    build:
      context: ./mu-dash  # Pointing to the directory where Dockerfile for React app is located
      dockerfile: Dockerfile
    
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_RUNTIME_ENV=docker
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./mu-dash:/app
    restart: always