FROM node:20-alpine

WORKDIR /app

RUN apt-get update && apt-get install -y procps

# Install global dev tools (optional)
RUN npm install -g concurrently
RUN npm install -g nodemon

# Frontend install
WORKDIR /app/mu-admin
COPY mu-admin/package*.json ./
RUN npm install

# Backend install
WORKDIR /app/mu-api
COPY mu-api/package*.json ./
RUN npm install

# Copy everything else
WORKDIR /app
COPY . .

# Start servers correctly
CMD concurrently \
  "nodemon --watch mu-api --ext js,ts --exec \"npm --prefix mu-api run dev\"" \
  "nodemon --watch mu-admin --ext js,ts,jsx,tsx --exec \"npm --prefix mu-admin run dev\"" \
  "nodemon --watch mu-hex-api --ext js,ts --exec \"npm --prefix mu-hex-api run dev\""